{% set name = "conan" %}
{% set version = "1.16.1" %}
{% set sha256 = "6ef76833b10db2af75fe3b3dc227970a54de2b83c7dd18d0ef15b9f62f9f5d20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - conan=conans.conan:run
    - conan_server=conans.conan_server:run
    - conan_build_info=conans.build_info.command:run
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pyjwt >=1.4.0,<2.0.0
    - requests >=2.7.0,<3.0.0
    - colorama >=0.3.3,<0.5.0
    - pyyaml >=3.11,<3.14.0
    - python-patch ==1.16
    - fasteners >=0.14.1
    - six >=1.10.0
    - python-node-semver ==0.6.1
    - distro >=1.0.2,<1.2.0
    - pylint >=1.9.3,!=2.3.0
    - future ==0.16.0
    - pygments >=2.0,<3.0
    - astroid >=1.6.5
    - deprecation >=2.0,<2.1
    - tqdm >=4.28.1,<5
    - jinja2 >=2.3,<3
    - bottle >=0.12.8,< 0.13
    - pluginbase >=0.5,< 1.0

test:
  imports:
    - conans
    - conans.build_info
    - conans.client
    - conans.client.build
    - conans.client.cmd
    - conans.client.conf
    - conans.client.generators
    - conans.client.rest
    - conans.client.store
    - conans.client.tools
    - conans.model
    - conans.search
    - conans.server
    - conans.server.conf
    - conans.server.crypto
    - conans.server.crypto.jwt
    - conans.server.rest
    - conans.server.service
    - conans.server.store
    - conans.util
  commands:
    - conan --help
    - conan_build_info --help

about:
  home: https://conan.io
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.md'
  summary: Conan C/C++ package manager
  doc_url: http://docs.conan.io/en/latest/
  dev_url: https://github.com/conan-io/conan

extra:
  recipe-maintainers:
    - windelbouwman
    - abloemert
    - memsharded
