{% set name = "conan" %}
{% set version = "2.12.2" %}
{% set sha256 = "b09ff3d7fe8101e3ef55fd0785ae9ffbcd9237ac427da88c975e8c52908ed4f7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - conan=conans.conan:run
    - conan_server=conans.conan_server:run
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    # client requirements
    - requests >=2.25,<3.0.0
    - urllib3 >=1.26.6,<1.27
    - colorama >=0.4.3,<0.5.0
    - pyyaml >=6.0,<7.0
    - patch-ng >=1.18.0, <1.19
    - fasteners >=0.15
    - distro >=1.4.0,<=1.8.0
    - jinja2 >=3.0,<4.0.0
    - python-dateutil >=2.8.0,<3
    # server requirements
    - bottle >=0.12.8,<0.13
    - pluginbase >=0.5
    - pyjwt >=2.4.0,<3.0.0

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - conans
    - conan
    - conan.tools
    - conan.tools.cmake
    - conan.tools.gnu
    - conan.tools.google
    - conan.tools.apple
    - conan.tools.meson
    - conan.tools.intel
    - conan.tools.microsoft
    - conan.tools.qbs
    - conan.tools.env
    - conan.tools.system
    - conan.tools.files
    - conan.tools.layout
    - conan.tools.scm
    - conan.tools.build
    - conan.errors
  commands:
    - pip check
    - conan --help

about:
  home: https://conan.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Conan C/C++ package manager
  doc_url: http://docs.conan.io/en/latest/
  dev_url: https://github.com/conan-io/conan

extra:
  recipe-maintainers:
    - abloemert
